### ISSUE TITLE
Themes!

### ISSUE THREAD

**Issue by mreishman** [mreishman/Log-Hog#25]
Add different themes (changes to color scheme, font, and sizes)

- [x] Menu in settings

- [x] Change most references to local images from core images

- [x] Move save new setting from page to upgrade logic (when changing css version)
          - [ ] (Leave out default selector during this though)
